# Generated by Django 5.2.3 on 2025-07-07 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la filiale')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name="Nombre d'interventions")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('query_counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Filiale',
                'verbose_name_plural': 'Filiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom de la machine')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name="Nombre d'interventions")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('query_counter', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterventionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique générée automatiquement', max_length=50, unique=True, verbose_name="Référence de l'intervention")),
                ('date_intervention', models.DateTimeField(verbose_name="Date de l'intervention")),
                ('contact', models.CharField(max_length=100, verbose_name='Contact')),
                ('numero_telephone', models.CharField(default='', max_length=20, verbose_name='Numéro de téléphone')),
                ('filiale', models.CharField(max_length=100, verbose_name='Filiale')),
                ('machine', models.CharField(max_length=200, verbose_name='Machine')),
                ('intervenants', models.TextField(verbose_name='Intervenant(s)')),
                ('responsables', models.TextField(verbose_name='Responsable(s)')),
                ('criticite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=10, verbose_name="Criticité de l'intervention")),
                ('diffuseur', models.CharField(max_length=100, verbose_name='Diffusé par')),
                ('objet', models.CharField(max_length=200, verbose_name="Objet de l'intervention")),
                ('description', models.TextField(verbose_name="Description de l'intervention")),
                ('recommandations', models.TextField(blank=True, null=True, verbose_name='Recommandations des intervenants')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('filiale_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='form.filiale', verbose_name='Filiale (objet)')),
                ('machine_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='form.machine', verbose_name='Machine (objet)')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='interventions/documents/', verbose_name='Fichier joint')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='form.interventionrequest', verbose_name='Intervention')),
            ],
            options={
                'verbose_name': "Document d'intervention",
                'verbose_name_plural': "Documents d'intervention",
            },
        ),
    ]
