# Generated by Django 5.2.3 on 2025-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrequest',
            name='objet',
            field=models.CharField(max_length=1000, verbose_name="Objet de l'intervention"),
        ),
    ]
